DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 448
  TEST:
    BATCH_SIZE: 500

OPTIM:
  NAME: 'sgd'
  #LR: 0.05
  LR: 0.5
  STAGED_LR: True
  NEW_LAYERS: ('backbone.layer1_adap', 'backbone.layer_adap', 'backbone.layer4_adap', 'backbone.layer2_adap', 'backbone.layer3_adap', 'backbone.layer4_new', 'adaptive_cls', 'classifier', 'backbone.dist_net_conv', 'backbone.block3_dida')
  BASE_LR_MULT: 0.1

  STEPSIZE: [4000]
  MAX_EPOCH: 4000
  LR_SCHEDULER: 'cosine'

TRAIN:
  COUNT_ITER: 'train_u'
  PRINT_FREQ: 10

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']

