DATALOADER:
  NUM_WORKERS: 2
  TRAIN_X:
    SAMPLER: 'RandomSampler'
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100

OPTIM:
  NAME: 'sgd'
  #LR: 0.00005
  LR: 0.01
  WEIGHT_DECAY: 0.001
  STAGED_LR: True
  NEW_LAYERS: ('head', 'backbone.layer_adap', 'backbone.layer4_adap', 'backbone.layer2_adap', 'backbone.layer3_adap', 'backbone.layer4_new', 'adaptive_cls', 'classifier', 'backbone.dist_net_conv')
  BASE_LR_MULT: 0.1

  MAX_EPOCH: 100
  LR_SCHEDULER: 'cosine'

