DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 32
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 32

OPTIM:
  NAME: 'adam'
  LR: 0.00005
  MAX_EPOCH: 100
  LR_SCHEDULER: 'cosine'
  #NEW_LAYERS: ['classifier']
  #BASE_LR_MULT: 0.1
  #STAGED_LR: True

TRAINER:
  FIXMATCH:
     STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']
     EMA_ALPHA: 0.999
