DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    SAMPLER: 'RandomSampler'
    BATCH_SIZE: 32
  TRAIN_U:
    SAME_AS_X: True
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 200
  LR_SCHEDULER: 'cosine'

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']
    EMA_ALPHA: 0.999

