INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'normalize']

DATASET:
  NAME: 'DomainNet'

MODEL:
  BACKBONE:
    NAME: 'resnet101'
  HEAD:
    NAME: 'visda_head'
    HIDDEN_LAYERS: [1024, 512]
    DROPOUT: 0.5

