INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'center_crop', 'normalize']

DATASET:
  NAME: 'VisDA17'

MODEL:
  BACKBONE:
    NAME: 'resnet101_ca'
  HEAD:
    NAME: 'visda_head'
    HIDDEN_LAYERS: [1000, 1000]
    DROPOUT: 0.5

TEST:
  PER_CLASS_RESULT: True
